package main

/* Views */

const VIEW_TEMPLATE = `package {{.Options.PackageName}}

/* *********************************************************** */
/* This file was automatically generated by pgtogogen.         */
/* Do not modify this file unless you know what you are doing. */
/* *********************************************************** */

import (	
	"sync"
	"github.com/silviucm/pgx"
	{{range $key, $value := .GoTypesToImport}}"{{$value}}"
	{{end}}
)


// this is a dummy variable, just to use the pgx package
var pgxPackageView{{.GoFriendlyName}}ReferenceErrDeadConn = pgx.ErrDeadConn

const {{.GoFriendlyName}}_DB_VIEW_NAME string = "{{.DbName}}"

type {{.GoFriendlyName}} struct {
	{{range .Columns}}// database field name: {{.DbName}}
	{{.GoName}} {{.GoType}}
	{{if .Nullable}}{{.GoName}}_IsNotNull bool // if true, it means the corresponding field does not currently carry a null value
	{{end}}
	{{end}}		
}

{{ $tableGoName := .GoFriendlyName}}
{{range .Columns}}func (t *{{$tableGoName}}) Set{{.GoName}}(val {{.GoType}} {{if .Nullable}}, notNull bool{{end}}) {
	t.{{.GoName}} = val
	{{if .Nullable}}t.{{.GoName}}_IsNotNull = notNull{{end}}
}
{{end}}

// fake, interal type to allow a singleton structure that would hold static-like methods
type t{{.GoFriendlyName}}Utils struct {
		
	// instance of a CacheFor{{.GoFriendlyName}} structure
	Cache CacheFor{{.GoFriendlyName}}		
		
}

{{if .IsMaterialized}}
{{$functionName := "RefreshMaterializedView"}}{{$sourceStructName := print "source" .GoFriendlyName}}
// Refreshes the materialized view and updates it with the latest data from the underlying 
// data entities
func (utilRef *t{{.GoFriendlyName}}Utils) {{$functionName}}()  error {
						
	var errorPrefix = "{{.GoFriendlyName}}Utils.{{$functionName}}() ERROR: "
	
	currentDbHandle := GetDb()
	if currentDbHandle == nil {
		return NewModelsErrorLocal(errorPrefix, "the database handle is nil")
	}
	
	_, err := currentDbHandle.Exec("REFRESH MATERIALIZED VIEW {{.DbName}};")
	if err != nil {
		return NewModelsError(errorPrefix + "currentDbHandle.Exec error:",err)
	}
	
	return  nil	
	
}
{{end}}
`

const VIEW_TEMPLATE_CUSTOM = `package {{.Options.PackageName}}

/* *********************************************************** **/
/* This file is generated by pgtogogen FIRST-TIME ONLY.         */
/* It will not subsequently overwrite it if it already exists.  */
/* Use this file to create your custom extension functionality. */
/* ************************************************************ */

/*
import (
	{{range $key, $value := .GoTypesToImport}}"{{$value}}"
	{{end}}	
)
*/

`
