package main

const BASE_DB_TYPES = `package {{.PackageName}}

/* ************************************************************* */
/* This file was automatically generated by pgtogogen.           */
/* Do not modify this file unless you know what you are doing.   */
/* ************************************************************* */

import (
	pgx "{{.PgxImport}}"	
	pgtype "{{.PgTypeImport}}"	
)

//
// DB types helper functions
//



`
